---

- name: "main | Install python{{ ansible_python.version.major }}-pip"
  package:
    name: "python{{ ansible_python.version.major }}-pip"

# - name: main | Install psycopg2-binary with pip
#   pip:
#     name: psycopg2-binary

# Manage databases
- include_tasks: dbs.yml

# Manage users
- include_tasks: users.yml
